# Generated by Django 4.2.4 on 2023-09-02 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_caducidad_fabricante', models.DateField(blank=True, null=True)),
                ('lote', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vacunatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=20)),
                ('nombre_encargado', models.CharField(max_length=100)),
                ('email_encargado', models.EmailField(max_length=100)),
                ('codigo_deis', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='VacunaStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField()),
                ('fecha_descongelacion', models.DateField(blank=True, null=True)),
                ('hora_descongelacion', models.TimeField(blank=True, null=True)),
                ('fecha_caducidad_descongelacion', models.DateField(blank=True, null=True)),
                ('tipo_vacuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.vacuna')),
                ('vacunatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.vacunatorio')),
            ],
        ),
        migrations.CreateModel(
            name='TraspasoVacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_traspaso', models.DateTimeField(auto_now_add=True)),
                ('cantidad_traspasada', models.PositiveIntegerField()),
                ('responsable_entrega', models.CharField(max_length=100)),
                ('responsable_recepcion', models.CharField(max_length=100)),
                ('vacuna_traspaso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traspasos_enviados', to='inventario.vacunastock')),
                ('vacunatorio_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.vacunatorio')),
            ],
        ),
        migrations.CreateModel(
            name='EliminacionVacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cantidad_eliminada', models.PositiveIntegerField()),
                ('responsable_eliminacion', models.CharField(max_length=100)),
                ('vacuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.vacunastock')),
            ],
        ),
        migrations.CreateModel(
            name='AdministracionVacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cantidad_administrada', models.PositiveIntegerField()),
                ('vacuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.vacunastock')),
            ],
        ),
    ]
