# Generated by Django 4.2.4 on 2023-09-02 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioVacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_caducidad_fabricante', models.DateField()),
                ('fecha_descongelacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_caducidad_descongelacion', models.DateTimeField(blank=True, null=True)),
                ('existe', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vacunatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TraspasoVacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_traspaso', models.DateTimeField()),
                ('cantidad_traspasada', models.PositiveIntegerField()),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traspasos_recibidos', to='inventario.vacunatorio')),
                ('inventario_vacuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.inventariovacuna')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traspasos_realizados', to='inventario.vacunatorio')),
            ],
        ),
        migrations.CreateModel(
            name='RetiroCamara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_retiro', models.DateTimeField()),
                ('cantidad_retirada', models.PositiveIntegerField()),
                ('inventario_vacuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.inventariovacuna')),
            ],
        ),
        migrations.AddField(
            model_name='inventariovacuna',
            name='vacuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.vacuna'),
        ),
        migrations.AddField(
            model_name='inventariovacuna',
            name='vacunatorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.vacunatorio'),
        ),
        migrations.CreateModel(
            name='EliminacionVacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_eliminacion', models.DateTimeField()),
                ('motivo_eliminacion', models.CharField(max_length=200)),
                ('inventario_vacuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.inventariovacuna')),
            ],
        ),
        migrations.CreateModel(
            name='AdministracionVacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_administracion', models.DateTimeField()),
                ('cantidad_administrada', models.PositiveIntegerField()),
                ('inventario_vacuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.inventariovacuna')),
            ],
        ),
    ]
