# Generated by Django 4.2.5 on 2023-09-21 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eliminacionvacuna',
            name='vacunatorio_eliminacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventario.vacunatorio'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TraspasoVacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_traspaso', models.DateTimeField(auto_now_add=True)),
                ('cantidad_traspasada', models.PositiveIntegerField()),
                ('is_accepted', models.BooleanField(blank=True, default=False)),
                ('responsable_entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traspasos_entrega', to=settings.AUTH_USER_MODEL)),
                ('responsable_recepcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traspasos_recepcion', to=settings.AUTH_USER_MODEL)),
                ('vacuna_traspaso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traspasos_enviados', to='inventario.vacunastock')),
                ('vacunatorio_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traspasos_destino', to='inventario.vacunatorio')),
                ('vacunatorio_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traspasos_origen', to='inventario.vacunatorio')),
            ],
        ),
    ]
