# Generated by Django 4.2.5 on 2023-10-28 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacunatorio',
            name='direccion',
        ),
        migrations.AddField(
            model_name='inventariovacuna',
            name='fecha_administracion',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='inventariovacuna',
            name='fecha_eliminacion',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='inventariovacuna',
            name='hora_descongelacion',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventariovacuna',
            name='lote',
            field=models.CharField(default='aaa', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventariovacuna',
            name='fecha_caducidad_descongelacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventariovacuna',
            name='fecha_descongelacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vacuna',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='vacunatorio',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
