# Generated by Django 4.2.5 on 2023-09-14 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_traspasovacuna'),
    ]

    operations = [
        migrations.AddField(
            model_name='eliminacionvacuna',
            name='vacunatorio_eliminacion',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='inventario.vacunatorio'),
            preserve_default=False,
        ),
    ]
