# Generated by Django 4.2.4 on 2023-08-22 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_vacunastock_hora_descongelacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacunastock',
            name='hora_descongelacion',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
