# Generated by Django 4.2.5 on 2023-09-21 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_eliminacionvacuna_vacunatorio_eliminacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traspasovacuna',
            name='is_accepted',
        ),
        migrations.RemoveField(
            model_name='vacunatorio',
            name='email_encargado',
        ),
        migrations.RemoveField(
            model_name='vacunatorio',
            name='nombre_encargado',
        ),
    ]
