# Generated by Django 4.2.5 on 2023-09-24 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_remove_traspasovacuna_is_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacuna',
            name='congelacion',
            field=models.BooleanField(default=True),
        ),
    ]
