# Generated by Django 4.2.5 on 2023-09-25 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_vacuna_congelacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetiroCamara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_retiro', models.DateField(auto_now_add=True)),
                ('cantidad_retiro', models.PositiveIntegerField()),
                ('vacuna_retiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retiro_camara', to='inventario.vacunastock')),
            ],
        ),
    ]
