# Generated by Django 4.2.5 on 2023-09-25 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_retirocamara'),
    ]

    operations = [
        migrations.AddField(
            model_name='retirocamara',
            name='vacunatorio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventario.vacunatorio'),
            preserve_default=False,
        ),
    ]
