# Generated by Django 4.2.4 on 2023-09-05 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_traspasovacuna_responsable_entrega_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traspasovacuna',
            name='is_accepted',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
