# Generated by Django 4.2.5 on 2023-09-25 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_retirocamara_vacunatorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retirocamara',
            name='vacuna_retiro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacuna_retiro_camara', to='inventario.vacunastock'),
        ),
    ]
