# Generated by Django 4.2.5 on 2023-10-25 02:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_alter_retirocamara_vacuna_retiro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administracionvacuna',
            name='fecha',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='eliminacionvacuna',
            name='fecha',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='retirocamara',
            name='fecha_retiro',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='traspasovacuna',
            name='fecha_traspaso',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
