# Generated by Django 4.2.5 on 2023-10-25 03:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_eliminacionvacuna_motivo_eliminacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retirocamara',
            name='fecha_retiro',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
