# Generated by Django 4.2.5 on 2023-10-26 12:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_alter_retirocamara_fecha_retiro'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacunastock',
            name='hora_caducidad_descongelacion',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RegistroInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('stock_inicial', models.PositiveIntegerField()),
                ('stock_final', models.PositiveIntegerField()),
                ('vacuna_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.vacunastock')),
            ],
        ),
    ]
