# Generated by Django 4.2.5 on 2023-10-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_vacunastock_hora_caducidad_descongelacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroinventario',
            name='stock_final',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registroinventario',
            name='stock_inicial',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
