# Generated by Django 4.2.5 on 2023-10-26 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_alter_traspasovacuna_fecha_traspaso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traspasovacuna',
            name='fecha_traspaso',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
