# Generated by Django 4.2.5 on 2023-10-26 15:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_alter_traspasovacuna_fecha_traspaso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='retirocamara',
            old_name='cantidad_retiro',
            new_name='cantidad_retirada',
        ),
        migrations.RenameField(
            model_name='retirocamara',
            old_name='vacunatorio',
            new_name='vacunatorio_retiro',
        ),
        migrations.RemoveField(
            model_name='retirocamara',
            name='fecha_retiro',
        ),
        migrations.AddField(
            model_name='registroinventario',
            name='administraciones',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registroinventario',
            name='eliminaciones',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registroinventario',
            name='retiros_camara',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registroinventario',
            name='traspasos_entrantes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registroinventario',
            name='traspasos_salientes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='retirocamara',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='retirocamara',
            name='responsable_retiro',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='retirocamara',
            name='vacuna_retiro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.vacunastock'),
        ),
    ]
