# Generated by Django 4.2.5 on 2023-10-26 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0021_alter_administracionvacuna_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eliminacionvacuna',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
